version: "3.9"

services:
  database:
    image: postgres:13-alpine
    ports:
      - 5432:5432
    volumes:
      - chat-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=chatdb
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbuser

  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - "./app:/app"
    command: >
      sh -c "python -u server.py runserver 0.0.0.0:8000"
    environment:
      - OPENAI_API_KEY=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
    depends_on:
      - database

  adminer:
    image: adminer
    restart: always
    depends_on:
      - database
    ports:
      - 8080:8080


volumes:
  chat-db-data: